name: Build Android APK

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0
        pip install cython==0.29.33

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev

    - name: Accept Android SDK licenses
      run: |
        yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"

    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << EOF
        [app]
        title = Bierwiegen
        package.name = bierwiegen
        package.domain = org.bierwiegen
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 1.0
        requirements = python3,kivy==2.1.0
        orientation = portrait
        fullscreen = 0
        android.permissions = INTERNET
        android.api = 33
        android.minapi = 21
        android.ndk = 27.2.12479018
        android.ndk_path = /usr/local/lib/android/sdk/ndk/27.2.12479018
        android.sdk_path = /usr/local/lib/android/sdk
        android.build_tools = 33.0.0
        android.accept_sdk_license = True
        android.gradle_dependencies = org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0
        android.skip_update = True
        [buildozer]
        log_level = 2
        warn_on_root = 1
        EOF

    - name: Debug Environment
      run: |
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
        ls -la /usr/local/lib/android/sdk/
        ls -la /usr/local/lib/android/sdk/ndk/
        ls -la /usr/local/lib/android/sdk/cmdline-tools/latest/bin/

    - name: Build with Buildozer
      env:
        BUILDOZER_WARN_ON_ROOT: 0
      run: |
        export PATH=$PATH:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/build-tools/33.0.0
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bierwiegen-app
        path: bin/*.apk
        retention-days: 90
