name: Build Android APK

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0
        pip install cython==0.29.33

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev

    - name: Download Android SDK & NDK
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/android-sdk
        cd ${GITHUB_WORKSPACE}/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools
        mv cmdline-tools latest
        mv latest cmdline-tools/
        export ANDROID_HOME=${GITHUB_WORKSPACE}/android-sdk
        export PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:${PATH}
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
        
        # Download NDK manually
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        mv android-ndk-r25b ndk/25.2.9519653

    - name: Build with Buildozer
      env:
        ANDROID_HOME: ${GITHUB_WORKSPACE}/android-sdk
        ANDROID_NDK_HOME: ${GITHUB_WORKSPACE}/android-sdk/ndk/25.2.9519653
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bierwiegen-app
        path: bin/*.apk
        retention-days: 90
